### ISSUE TITLE
Create slides for legal session.

### ISSUE THREAD

**Issue by Treblesteph** [ContentMine/workshops#5]

**Comment by CharlesOppenheim** [comment]
Happy to comment on any draft

**Comment by Treblesteph** [comment]
Great, thanks very much @CharlesOppenheim. I will be going through your slides and making versions that match up with our brand. So that we can make sure we are on the same page, it might be helpful to go through them with you first, maybe we could skype some time?

**Comment by CharlesOppenheim** [comment]
Best times for me to Skype are Thu morning or any time Friday. Any good?
Charles
Professor Charles Oppenheim
----Original message----
From : notifications@github.com
Date : 23/02/2015 - 14:04 (GMT)
To : workshops@noreply.github.com
Cc : c.oppenheim@btinternet.com
Subject : Re: [workshops] Create slides for legal session. (#5)
Great, thanks very much @CharlesOppenheim. I will be going through your slides and making versions that match up with our brand. So that we can make sure we are on the same page, it might be helpful to go through them with you first, maybe we could skype some time?

**Comment by Treblesteph** [comment]
@CharlesOppenheim thursday morning would be great, how about 10:30?

**Comment by CharlesOppenheim** [comment]
Perfect!  I am charles.oppenheim1 on Skype.
Charles
Professor Charles Oppenheim
----Original message----
From : notifications@github.com
Date : 23/02/2015 - 16:56 (GMT)
To : workshops@noreply.github.com
Cc : c.oppenheim@btinternet.com
Subject : Re: [workshops] Create slides for legal session. (#5)
@CharlesOppenheim thursday morning would be great, how about 10:30?

**Comment by Treblesteph** [comment]
Done in commit fa066301d3025a6e43f2e15f67e73b3036805154.
